version: "2.3"

services:
  prometeus:
    container_name: prometheus
    image: prom/prometheus:v2.2.0
    cpus: 1
    mem_limit: 1024m
    memswap_limit: 1024m
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    hostname: prometheus.monitoring
    extra_hosts:
      - "grafana.monitoring:172.16.239.11"
    networks:
      monitoring:
        ipv4_address: 172.16.239.10
  grafana:
    container_name: grafana
    image: grafana/grafana:5.0.0
    cpus: 1
    mem_limit: 1024m
    memswap_limit: 1024m
    restart: always
    hostname: grafana.monitoring
    ports:
      - "3100:3000"
    extra_hosts:
      - "prometheus.monitoring:172.16.239.10"
    environment:
      - GF_SERVER_ROOT_URL=https://awesome.wuxinwei.org
      - GF_SECURITY_ADMIN_PASSWORD=b3525466
    networks:
      monitoring:
        ipv4_address: 172.16.239.11

networks:
  monitoring:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24
